version: "3.9"
services:
  db:
    image: postgres:16-alpine
    container_name: ecom-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ecom_farmacia
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    container_name: ecom-redis
    ports:
      - "6379:6379"
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: ecom-api
    environment:
      - NODE_ENV=production
      - PORT=3002
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_NAME=ecom_farmacia
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "3002:3002"
    depends_on:
      - db
      - redis
  admin:
    build:
      context: .
      dockerfile: apps/admin/Dockerfile
    container_name: ecom-admin
    environment:
      - NODE_ENV=production
      - PORT=3001
    ports:
      - "3001:3001"
    depends_on:
      - api
  storefront:
    build:
      context: .
      dockerfile: apps/storefront/Dockerfile
    container_name: ecom-storefront
    environment:
      - NODE_ENV=production
      - PORT=3000
    ports:
      - "3000:3000"
    depends_on:
      - api

volumes:
  pgdata:


