version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: ecom-api
    environment:
      - NODE_ENV=production
      - PORT=3002
    ports:
      - "3002:3002"
  admin:
    build:
      context: .
      dockerfile: apps/admin/Dockerfile
    container_name: ecom-admin
    environment:
      - NODE_ENV=production
      - PORT=3001
    ports:
      - "3001:3001"
    depends_on:
      - api
  storefront:
    build:
      context: .
      dockerfile: apps/storefront/Dockerfile
    container_name: ecom-storefront
    environment:
      - NODE_ENV=production
      - PORT=3000
    ports:
      - "3000:3000"
    depends_on:
      - api


