name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Enable corepack
        run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm -w install --no-frozen-lockfile
      - name: Lint
        run: pnpm -w lint
      - name: Typecheck
        run: pnpm -w typecheck
      - name: Test
        run: pnpm -w test
      - name: Build
        run: pnpm -w build

  docker:
    runs-on: ubuntu-latest
    needs: build-test
    strategy:
      fail-fast: false
      matrix:
        app: [storefront, admin, api]
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          context: .
          file: apps/${{ matrix.app }}/Dockerfile
          push: false
          tags: ecom-farmacia/${{ matrix.app }}:ci


